### ISSUE TITLE
issue - values repeated

### ISSUE THREAD

**Issue by jbarojas** [elmolm/amazon-cognito-java#1]
When the list of users is higher than the limit, always is repeated the values. You should set the variable **userTypeList** again.
To fix this issue, you should set the variable in line 84 of class: **AmazonCognitoConnector.java**
userTypeList = result.getUsers();

thanks for the code, it is very useful.

Jahir Barojas

**Comment by elmolm** [comment]
Thank you for the feedback. I fixed the bug!
